### PR TITLE
Add GroupSearch and LoadAllGroups

### PR DESCRIPTION
**Pull request by itdove**
Signed-off-by: Dominique Vernier <dvernier@redhat.com>

https://github.com/stolostron/backlog/issues/19846

/hold

### CODE REVIEW

**Review by vidyanambiar — COMMENTED** [review]
@itdove The PR description mentions GroupSearch as well. Did you intend to commit something related to LDAP group search as part of this PR? 
If not, then this looks good and I'll go ahead and approve 👍

**Comment by itdove** [comment]
No the groupsearch was already in the code

**Review by vidyanambiar — APPROVED** [review]
/lgtm

**Pull request merged**
